GET http://localhost:3001/usuario

######

POST http://localhost:3001/usuario
Content-Type: application/json

{
    "nombre": "Alonso",
    "apellido": "Caceres",
    "correo": "alonsoCaceres@yopmail.com",
    "contrasena": "EresONoEres"
}

######

POST http://localhost:3001/usuario
Content-Type: application/json

{
    "nombre": "Luigui",
    "apellido": "Paredes",
    "correo": "luiguiParedes@yopmail.com",
    "contrasena": "holamundo"
}

######

GET http://localhost:3001/usuario/2

######

DELETE http://localhost:3001/usuario/1
Content-Type: application/json

######

GET http://localhost:3001/pre_armado_producto

######

POST http://localhost:3001/pre_armado_producto
Content-Type: application/json

{
    "pre_armado_id": 1,
    "producto_id": 1
}

######

GET http://localhost:3001/pre_armado_producto/1