GET https://proyectogrupalbackend-production.up.railway.app/usuario

######g

POST https://proyectogrupalbackend-production.up.railway.app/usuario
Content-Type: application/json

{
    "nombre": "Alonso",
    "apellido": "Caceres",
    "correo": "alonsoCaceres@yopmail.com",
    "contrasena": "EresONoEres"
}

######

POST https://proyectogrupalbackend-production.up.railway.app/usuario
Content-Type: application/json

{
    "nombre": "Luigui",
    "apellido": "Paredes",
    "correo": "luiguiParedes@yopmail.com",
    "contrasena": "holamundo"
}

######

GET https://proyectogrupalbackend-production.up.railway.app/usuario/2

######